### ISSUE TITLE
ТЗ

### ISSUE THREAD

**Issue by Pro100ore** [Pro100ore/RPS1#1]
[ТЗ](https://github.com/Pro100ore/RPS1/files/2433741/_.docx)

**Comment by wldmr-key** [comment]
ок, начало хорошее. В смысле, хорошо, что хоть что-то началось
Что касается ТЗ, то, увы, смысл работы совершенно непонятен.
Что такое "большая компьютерная периферия"? Что это за функциональное назначение? Кому нужно "упрощение взаимодействия с периферией"? Кому с ней сложно взаимодействовать и почему? 
С русским языком колоссальные проблемы. Прочитай сам этот текст и
а) постарайся ясно изложить проблему и задание на ее решение
б) исправить все ляпы

**Comment by Pro100ore** [comment]
@wldmr-key, подправил.

4. Технико-экономические показатели
4.1 Экономические преимущества разработки

Данный программный продукт предполагается для использования в компании ГБУЗ КО «Городская поликлиника» сотрудниками отдела АСУ в ежедневном режиме. 
•	Преимущества разработки является, создание приложение сотрудником предприятия.
•	Уменьшение расходов из-за повышения контроля слежения имущества 
•	Упрощение интерфейса, так как было прямое указание на ненужный функционал и сложный интерфейс аналогов на рыке.

**Comment by wldmr-key** [comment]
Нет, проблемы с изложением и русским языком остались. Неужели ты не читаешь то, что пишешь и не видишь несогласованных падежей и отсутствие смысла и стиля ("уменьшение расходников")
Прочитай ГОСТ, а также https://habr.com/post/328822/ и https://gaperton.livejournal.com/49867.html, а также, возможно, другие материалы, чтобы понять, что ТЗ - это не отписка, а средство согласовать требования к процессу разработки программной системы

**Comment by Pro100ore** [comment]
@wldmr-key 

4. Технико-экономические показатели
4.1 Экономические преимущества разработки

Данный программный продукт предполагается для использования в компании ГБУЗ КО «Городская поликлиника» сотрудниками отдела АСУ в ежедневном режиме.
•	Преимущества разработки является, создание приложение сотрудником предприятия.
•	Уменьшение расходов из-за повышения контроля слежения за имуществом.
•	Увеличение расходных материалов на складе, сокращение их неконтролируемых перемещений, что приводит к экономному и контролируемому данного продукта, а также ускорению рабочего процесса.
•	Составление отчёта о передвижении каждой единицы.
•	Упрощение интерфейса, так как было прямое указание на ненужный функционал и сложный интерфейс аналогов на рынке.

**Comment by wldmr-key** [comment]
такой стиль общения не пойдет. Я жду от тебя технического задания, которое написано на русском языке и из которого можно понять, что требуется от разрабатываемой программной системы. Редактированием двух не самых важных абзацев этого не добиться

**Comment by Pro100ore** [comment]
[ТЗ_15.10.2018.docx](https://github.com/Pro100ore/RPS1/files/2478402/_15.10.2018.docx)

@wldmr-key , в разделе 2.1 это наименование темы, в 2.2 не вижу где у меня программа являлается результатом всего.

**Comment by wldmr-key** [comment]
у тебя есть знакомые, которые любят читать? Дай им прочитать свой текст и показать смысловые и стилистические ошибки

**Comment by Pro100ore** [comment]
[ТЗ_18-10-2018.docx](https://github.com/Pro100ore/RPS1/files/2493121/_18-10-2018.docx)

@wldmr-key

**Comment by wldmr-key** [comment]
плохой знакомый! Ищи другого
И, пока ищешь, постарайся так описать функции программы, чтобы было понятно, что она делает

**Comment by Pro100ore** [comment]
[TZ_18-10-2018.docx](https://github.com/Pro100ore/RPS1/files/2493356/TZ_18-10-2018.docx)

@wldmr-key перелопатил, посмотрите пожалуйста

**Comment by wldmr-key** [comment]
с языком стало намного, намного лучше. Осталось провести еще одно вычитывание и избавитья от 4-5 унаследованных перлов.
Со смыслом похуже. Стоит пару раз прочитать текст внимательно и убрать совсем уж бессмысленные вещи - типа защищенной программной системы,  сюрреалистичные экономические преимущества и т.п.
И, главное,  постарайся так описать функции программы, чтобы было понятно, что она делает. Требовать от программы, чтобы она обеспечивала возможность (!) создавать запись (какую? для кого? когда? зачем?)  - это за гранью добра и зла! Где периферия и "расходники" в твоих требованиях?

**Comment by Pro100ore** [comment]
[ТЗ_30-10-2018.docx](https://github.com/Pro100ore/RPS1/files/2530625/_30-10-2018.docx)

@wldmr-key

**Comment by wldmr-key** [comment]
ох, ну хотя бы так! Давай, уж, дальше продвигайся
Но к сдаче работы грамматические ошибки все же поправь
