### ISSUE TITLE
РПЗ

### ISSUE THREAD

**Issue by Pro100ore** [Pro100ore/RPS1#10]
@wldmr-key , первый вариант. Не знаю что делать с IDF0 диаграммой, не получается у меня.

[РПЗ РПС.docx](https://github.com/Pro100ore/RPS1/files/2690372/default.docx)

**Comment by wldmr-key** [comment]
с диаграммой я тебе советовал ничего не делать и остаюсь при своем мнении. Текст плох с точки зрения русского языка, но уже не ужасен, как раньше. Технологической части нет, но, надеюсь, она появится. Кода нет, но, надеюсь, он будет написан ли хотя бы создана иллюзия его наличия. Логическая схема БД, по-прежнему, не выдерживает никакой критики
