### ISSUE TITLE
Описание предметной области

### ISSUE THREAD

**Issue by Pro100ore** [Pro100ore/RPS1#2]
[Предметная область](https://github.com/Pro100ore/RPS1/files/2538417/PredObl_01-11-2018.docx)

@wldmr-key

**Comment by Pro100ore** [comment]
Начинаю переделывать предметную область, здесь только начало...

[Предм_обл_22-11-2018.docx](https://github.com/Pro100ore/RPS1/files/2607902/_._22-11-2018.docx)

@wldmr-key

**Comment by wldmr-key** [comment]
ужасно. Но, конечно, лучше, чем ничего

**Comment by Pro100ore** [comment]
[Предметная_обл_02-12-2018.docx](https://github.com/Pro100ore/RPS1/files/2637059/_._02-12-2018.docx)
@wldmr-key

**Comment by wldmr-key** [comment]
Ох... Я не буду притворяться еще тупее, чем я есть на самом деле и говорить, что из твоего текста ничего нельзя понять ))
Понять все можно, но это изложено так ужасно, что, если в комиссии кто решит это прочитать, то на этом защита и закончится. Я не учу вас русскому языку, поэтому попроси помощи у кого-нибудь, кто с ним в ладах и отредактируй текст.
Обрати внимание не только на синтаксис и пунктуацию, но и на смысл.  Обороты типа "учет осуществляет хранение",  "учет должен выполнять учет" и им подобные должны быть исправлены.

**Comment by Pro100ore** [comment]
@wldmr-key правил смысл и русский
[Uploading Predmetnaya_obl_08-12-2018.docx…]()

**Comment by wldmr-key** [comment]
ссылочка плохая получилась - не туда ведет

**Comment by Pro100ore** [comment]
@wldmr-key 

 https://drive.google.com/open?id=13_28BFuxZNYHrE7hMnmawdscyH1x-Xxr
