### ISSUE TITLE
Постановка задачи проектирования

### ISSUE THREAD

**Issue by Pro100ore** [Pro100ore/RPS1#4]
@wldmr-key

[Постановка задачи проектирования](https://github.com/Pro100ore/RPS1/files/2607661/Postanovka_zadachi_proektirovania.docx)

**Comment by wldmr-key** [comment]
я так понимаю постановка должна следовать из описания предметной области, которого пока нет. Тем не менее, стоит внимательнее относится к русскому языку и логике изложения

**Comment by Pro100ore** [comment]
@wldmr-key в методичке постановка идёт первой, а после уже предметная область

**Comment by wldmr-key** [comment]
тогда, бессмысленность приведенной постановки становится еще более очевидной

**Comment by Pro100ore** [comment]
@wldmr-key 
[Postanovka_zadachi_proektirovania (1).docx](https://github.com/Pro100ore/RPS1/files/2686766/Postanovka_zadachi_proektirovania.1.docx)

**Comment by wldmr-key** [comment]
разработка - это не средство, а цель. Сойдет...
