### ISSUE TITLE
Сравнение аналогов

### ISSUE THREAD

**Issue by Pro100ore** [Pro100ore/RPS1#5]
[Аналоги.docx](https://github.com/Pro100ore/RPS1/files/2660665/default.docx)

@wldmr-key

**Comment by wldmr-key** [comment]
обзор хороший, но несколько не из твоей предметной области - ты, ведь, не со складом работаешь? В принципе и из него можно сделать нормальные выводы о том, какие из рассмотренных функций для тебя хороши, а какие - нет

**Comment by Pro100ore** [comment]
@wldmr-key  верно, не со складом в полном смысле этого слова как описано в аналогах, но мы храним периферию, проводим инвентаризацию, принимаем и отдаём.

**Comment by Pro100ore** [comment]
[Analogi_v2.docx](https://github.com/Pro100ore/RPS1/files/2667244/Analogi_v2.docx)

@wldmr-key добавил вывод.

**Comment by wldmr-key** [comment]
пойдет (имей, правда, в виду - что за все слова в РПЗ ты отвечаешь - мне некоторые выводы показались трудно доказуемыми) - двигай дальше
