### ISSUE TITLE
IDEF0

### ISSUE THREAD

**Issue by Pro100ore** [Pro100ore/RPS1#6]
Пробую, что-то нарисовать понятное. Сталкиваюсь с проблемой выделения главного процесса. У меня идёт и хранение и выдача периферии. Остановился на том, что главное это автоматизация ввода данных.

@wldmr-key

[IDEF0-test.pdf](https://github.com/Pro100ore/RPS1/files/2667217/IDEF0-test.pdf)

**Comment by wldmr-key** [comment]
именно! IDEF - отличное иллюстративное средство, если есть что иллюстрировать. В твоем случае - я, честно говоря, не вижу процесса, который твоя схема помогает понять - скорее, запутывает. так что или ищи более хороший пример, или, ну его - этот идеф

**Comment by Pro100ore** [comment]
@wldmr-key  его  не обязательно делать? Тогда я сам могу рассказать, если буду вопросы или как?
