### ISSUE TITLE
Концептуальная

### ISSUE THREAD

**Issue by Pro100ore** [Pro100ore/RPS1#7]
@wldmr-key

[Концептуальная модель.pdf](https://github.com/Pro100ore/RPS1/files/2685949/default.pdf)

**Comment by wldmr-key** [comment]
В данном случае использование нотации Чена не очень мотивировано - какой смысл в слове "содержит" повторяющемся 6 раз при том, что слово "создает" выглядит совсем непонятно - только захламление схемы. Что за непонятные стрелочки между пользователем и рабочим местом - что они означают?

**Comment by Pro100ore** [comment]
@wldmr-key 

![default](https://user-images.githubusercontent.com/30180915/50139735-9133bf80-02b3-11e9-8474-83174353b000.png)

**Comment by wldmr-key** [comment]
не находишь, что так нагляднее? ок, имей только в виду, что при презентации (да и в печатном виде, если будешь печатать не в цвете) такая картинка смотреться не будет
